#! /bin/sh

#############
# AUTOSTART #
#############

#/home/murasaki/.local/bin/fehbg &
#/usr/bin/emacs --daemon &
#/home/murasaki/.config/polybar/launch.sh &

#picom &
#dunst &
#lxpolkit &

#xsetroot -cursor_name left_ptr &
#pgrep -x sxhkd > /dev/null || sxhkd &
#[ $[ $RANDOM % 6] = 0 ] && mpv --fullscreen --start=11:04.50 '/home/murasaki/Videos/tyler.webm'|| mpv --fullscreen '/home/murasaki/Videos/tyler.webm' &


###########
# MONITOR #
###########

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#########
# RULES #
#########

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
