#! /bin/sh



###########
# MONITOR #
###########

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          12
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config -m eDP-1 top_padding 48


#########
# RULES #
#########

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
